# Generated by Django 4.2.2 on 2023-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('newsapp_type', models.CharField(choices=[('1', 'Urgent'), ('2', 'Regular'), ('3', 'Low')], default='2', max_length=1)),
            ],
        ),
    ]
