# Generated by Django 4.2.2 on 2023-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_newsapp_type_news_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publication_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('1', 'Political'), ('2', 'Business'), ('3', 'International'), ('4', 'National'), ('5', 'Lifestyle'), ('6', 'Sport'), ('7', 'Entertainment'), ('8', 'Crime')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
