# Generated by Django 4.2.2 on 2023-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_publication_date_news_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('1', 'Political'), ('2', 'Business'), ('3', 'International'), ('4', 'National'), ('5', 'Lifestyle'), ('6', 'Sport'), ('7', 'Cultural'), ('8', 'Crime')], default='4', max_length=1),
        ),
    ]
