# Generated by Django 4.2.2 on 2023-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_news_date_alter_news_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
