# Generated by Django 4.2.2 on 2023-08-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
