# Generated by Django 4.2.4 on 2023-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
