# Generated by Django 4.2.2 on 2023-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_subscriber_subscribed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
