# Generated by Django 4.2.4 on 2023-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_teammember_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=9)),
                ('about', models.TextField(max_length=1000)),
                ('mission', models.TextField(max_length=1000)),
                ('latest_news_text1', models.TextField(max_length=1000)),
                ('latest_news_text2', models.TextField(max_length=1000)),
                ('about_team', models.TextField(max_length=1000)),
            ],
        ),
    ]
