# Generated by Django 4.2.2 on 2023-09-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
